add section deation
EduardHrebeniuk/wedovio pull request #1
Opened 2022-10-27 08:57 UTC by GabiKovtun

Проки що дала на перевіку лише Едуардові, бо більше нікого ще нема.)))

2022-10-27 12:21 UTC, EduardHrebeniuk requested changes
FontAwesome- це не font-family, це додаткова  платaорма накшталт google fonts  яку можна підключити( якщо я правильно зрозумів) в figma, чому вона така вказана я не знаю. тож просто задай poppins.

2022-10-27 14:29 UTC, EduardHrebeniuk approved these changes

2022-10-28 16:01 UTC, Exc3ls10r commented on css/styles.css
> +  position: relative;
Є сумніви що це потрібно

2022-10-28 16:04 UTC, Exc3ls10r commented on css/styles.css
> +  font-weight: 700;
Це заголовок. 700 не потрібно

2022-10-28 16:09 UTC, Exc3ls10r commented on css/styles.css
> +  font-style: normal;
Мабуть нормал також можна не писати

2022-10-28 16:11 UTC, Exc3ls10r commented on css/styles.css
> +  font-weight: 400;
Думаю що 400 не потрібне

2022-10-28 16:14 UTC, Exc3ls10r commented on css/styles.css
> +  text-decoration-line: underline;
Підкреслювання за замовчуванням

2022-10-28 16:17 UTC, Exc3ls10r commented on css/styles.css
> +  transform: translateY(-50% 0);
DevTools дуже не подобається

2022-10-28 16:28 UTC, Exc3ls10r requested changes
Будь ласка, виправте позиціонування нижнього блоку

2022-10-28 16:28 UTC, Exc3ls10r commented on css/styles.css
> +  left: 0;
Єдине з чим поки що не згоден) Цей блок при позиціонуванні притискається до лівого краю <section>, а не повинен. При 1920х1080 виглядає вже погано. На скільки розумію краще було б, у данному випадку позиціонувати від краю контейнера left: -165px; ...

Вибачте за прискіпливість (якщо було занадто, то це було в останній раз!)
:-))

2022-10-29 01:15 UTC, EduardHrebeniuk approved these changes

2022-10-29 01:42 UTC, Exc3ls10r approved these changes

2022-10-29 16:02 UTC, closed without merging